### ISSUE TITLE
Where is the function?

### ISSUE THREAD

**Issue by carlosmax3D** [Samson-Mano/opengl_textrendering#1]
You mentioned the use of a function called render_text() but it is not in the project

**Comment by Samson-Mano** [comment]
Updated the function name to paint_text(). This is the flow is the following 1) geom.set_geometry(); where the all_labels.init(); is called which creates the font library, main_font.create_atlas(); also the labels are added next. The painting is done in 2) geom.paint_geometry() where the all_labels.paint_text(); is called which paints all the labels at once.
